apiVersion: v1
kind: Service
metadata:
  name: skedly-api
  labels:
    app: skedly-api
spec:
  type: NodePort
  selector:
    app: skedly-api
  ports:
    - port: 80
      targetPort: 5010
      protocol: TCP
      # Local testing.
      nodePort: 30001
