apiVersion: v1
kind: Service
metadata:
  name: skedly-api
spec:
  selector:
    app: skedly-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      # Local testing.
      nodePort: 30001
  type: NodePort
