apiVersion: v1
kind: Service
metadata:
  name: skedly-ui
  labels:
    app: skedly-ui
spec:
  type: NodePort
  selector:
    app: skedly-ui
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      # Local testing.
      nodePort: 30000
